local _, Lang = ...;

local L = Lang.L

local Dialects = {

	[L["Gilnean"]] = {
		-- common speech
		["talk"]			= "gab",
		["talking"]			= "gabbin'",
		["going"]			= "goin'",
		["telling"]			= "tellin'",
		["hear"]			= "'ear",
		["hearing"]			= "'earin'",
		["seeing"]			= "seein'",
		["think"]			= "reckon",
		["thinking"]		= "reckonin'",
		["maybe"]			= "mayhap",
		["perhaps"]			= "per'aps",
		["very"]			= "right",
		["really"]			= "proper",

		-- greetings & reactions
		["hey"]				= "oi",
		["hello"]			= "'ello",
		["hi"]				= "oi",
		["goodbye"]			= "cheerio",
		["bye"]				= "ta",
		["yes"]				= "aye",
		["yeah"]			= "aye",
		["no"]				= "nah",
		["wow"]				= "blimey",
		["oh no"]			= "bloody hell",

		-- pronouns & contractions
		["you"]				= "ya'",
		["your"]			= "yer",
		["yours"]			= "yers",
		["yourself"]		= "yerself",
		["them"]			= "'em",

		["you are"]			= "ya're",
		["you're"]			= "ya're",
		["you were"]		= "ya'were",
		["you have"]		= "ya've",
		["you had"]			= "yah'd",
		["you would"]		= "yah'd",

		-- negation & emphasis
		["not"]				= "no'",
		["isn't"]			= "ain't",
		["aren't"]			= "ain't",
		--["wasn't"]			= "ain't",
		--["weren't"]			= "ain't",
		--["can't"]			= "canna'",
		--["couldn't"]		= "couldna'",
		["don't"]			= "dunna'",
		--["doesn't"]			= "dunna'",
		["won't"]			= "won't",
		["never"]			= "niver",
		["nothing"]			= "nothin'",
		["something"]		= "sumthin'",
		["anything"]		= "anythin'",
		["everything"]		= "ev'rythin'",

		-- question words
		["what"]			= "wot",
		--["where"]			= "wer",
		--["when"]			= "wen",
		["why"]				= "wot for",
		["how"]				= "'ow",
		["whatever"]		= "wotevah",
		--["whenever"]		= "wenevah",
		--["wherever"]		= "werevah",

		-- time & state
		["was"]				= "wus",
		["been"]			= "been",
		["going"]			= "goin'",
		["coming"]			= "comin'",
		["doing"]			= "doin'",

		-- social terms
		["friend"]			= "mate",
		["friends"]			= "mates",
		["man"]				= "bloke",
		["boy"]				= "lad",
		["girl"]			= "lass",
		--["child"]			= "bairn",
		--["children"]		= "bairns",
		["people"]			= "folk",

		-- emotion & attitude
		["angry"]			= "cross",
		["mad"]				= "barmy",
		["crazy"]			= "barmy",
		["afraid"]			= "afeared",
		["tired"]			= "knackered",
		["hungry"]			= "peckish",
		["drunk"]			= "sozzled",

		-- profanity
		["damn"]			= "blasted",
		["idiot"]			= "daft sod",
		["fool"]			= "dafty",

	},

	[L["Dwarvish"]] = {
		-- greetings, farewells, & social speech
		["hello"]			= "hullo",
		["hi"]				= "haye",
		["hey"]				= "oi",
		["greetings"]		= "well met",

		["morning"]	= "mornin'",
		["evening"]	= "evenin'",

		["welcome"]			= "come in from the cold",
		["thanks"]			= "much obliged",
		["thank you"]		= "much obliged",
		["sorry"] 			= "no harm meant",

		-- pronouns & contractions
		["you"]				= "ye",
		["your"]			= "yer",
		["yours"]			= "yers",
		["yourself"]		= "yerself",

		["my"]				= "me",

		["them"]			= "'em",

		["you're"]			= "ye're",
		["you have"]		= "ye've",
		["you will"]		= "ye'll",

		-- negation & emphasis
		["not"]				= "nae",
		["never"]			= "ne'er",
		["nothing"]			= "nothin'",
		["anything"]		= "anythin'",
		["everything"]		= "ev'rythin'",

		["isn't"]			= "innae",
		["aren't"]			= "aennae",
		["wasn't"]			= "wasnae",
		["weren't"]			= "werenae",

		["very"]			= "right",
		["really"]			= "proper",
		["quite"]			= "fair",

		-- thought, speech, & knowledge
		["thinking"]		= "thinkin'",
		["hearing"]		= "hear'n",

		-- size, age, & time
		["small"]			= "wee",
		["little"]			= "li'l",
		["big"]				= "great",
		["huge"]			= "mighty",

		["old"]				= "ol'",
		["older"]			= "elder",

		["soon"]			= "afore long",

		-- people & social labels
		["people"]			= "folk",

		["boy"]				= "lad",
		["girl"]			= "lass",
		["child"]			= "bairn",
		["children"]		= "bairns",

		["enemy"]			= "foe",
		["enemies"]			= "foes",

		-- insults & profanity
		["idiot"]			= "idjit",
		["moron"]			= "daft sod",
		["fool"]			= "bampot",

		-- craft, stone, & dwarven worldview
		["toiling"]			= "toilin'",

		-- drinking & sustenance
		["alcohol"]			= "ale",

		["hungry"]			= "peckish",

		-- emotional states
		["angry"]			= "sore",
		["mad"]				= "riled",
		["tired"]			= "weary",
		["afraid"]			= "uneasy",
	},

	[L["Draenei"]] = {
		-- endings
		["thinking"]		= "thinkink",
		["talking"]			= "talkink",
		["walking"]			= "walkink",
		["fighting"]		= "fightink",
		["running"]			= "runnink",
		["working"]			= "workink",
		["looking"]			= "lookink",
		["feeling"]			= "feelink",
		["waiting"]			= "waitink",
		["casting"]			= "castink",
		["moving"]			= "movink",
		["going"]			= "goink",
	},


	[L["Thalassian"]] = {
		-- de-contract, overly formal
		["gonna"]			= "going to",
		["'em"]				= "them",
		["'bout"]			= "about",
		["'cause"]			= "because",
		["cuz"]				= "because",
		["'cept"]			= "except",
		["c'mon"]			= "come on",
		["'n"]				= "and",
		["'n'"]				= "and",
		["n"]				= "and",
		["a'ight"]			= "alright",
		["ain't"]			= "is not",
		["amn't"]			= "am not",
		["aren't"]			= "are not",
		["can't"]			= "cannot",
		["cap'n"]			= "captain",
		["could've"]		= "could have",
		["couldn't"]		= "could not",
		["couldn't've"]		= "could not have",
		["cuppa"]			= "cup of",
		["daren't"]			= "dare not",
		["daresn't"]		= "dare not",
		["dasn't"]			= "dare not",
		["didn't"]			= "did not",
		["doesn't"]			= "does not",
		["don't"]			= "do not",
		["dunno"]			= "do not know",
		["d'ye"]			= "do you",
		["d'ya"]			= "do you",
		["'gainst"]			= "against",
		["g'day"]			= "good day",
		["gimme"]			= "give me",
		["giv'n"]			= "given",
		["hadn't"]			= "had not",
		["had've"]			= "had have",
		["hasn't"]			= "has not",
		["he'll"]			= "he will",
		["here's"]			= "here is",
		["how'd"]			= "how did",
		["how'll"]			= "how will",
		["how're"]			= "how are",
		["i'd"]				= "i would",
		["i'd've"]			= "i would have",
		["i'd'nt"]			= "i would not",
		["if'n"]			= "if and when",
		["i'll"]			= "i will",
		["i'm"]				= "i am",
		["i'm'onna"]		= "i am going to",
		["imma"]			= "i am going to",
		["i'm'o"]			= "i am going to",
		["i'm'na"]			= "i am going to",
		["innit"]			= "isn't it",
		["i've"]			= "i have",
		["isn't"]			= "is not",
		["it'd"]			= "it would",
		["it'll"]			= "it will",
		["it's"]			= "it's",
		["kinda"]			= "kind of",
		["lemme"]			= "let me",
		["lemmi"]			= "let me",
		["let's"]			= "let us",
		["may've"]			= "may have",
		["methinks"]		= "i think",
		["mightn't"]		= "might not",
		["might've"]		= "might have",
		["mine's"]			= "mine is",
		["mustn't"]			= "must not",
		["mustn't've"]		= "must not have",
		["must've"]			= "must have",
		["'neath"]			= "beneath",
		["needn't"]			= "need not",
		["ne'er"]			= "never",
		["o'clock"]			= "of the clock",
		["o'er"]			= "over",
		["ol'"]				= "old",
		["ought've"]		= "ought have",
		["oughtn't"]		= "ought not",
		["oughtn't've"]		= "ought not have",
		["'round"]			= "around",
		["shalln't"]		= "shall not",
		["shan'"]			= "shall not",
		["shan't"]			= "shall not",
		["should've"]		= "should have",
		["shouldn't"]		= "should not",
		["shouldn't've"]	= "should not have",
		["so're"]			= "so are",
		["so've"]			= "so have",
		["that're"]			= "that are",
		["there'll"]		= "there will",
		["there're"]		= "there are",
		["these're"]		= "these are",
		["these've"]		= "these have",
		["they'll"]			= "they will",
		["they've"]			= "they have",
		["those're"]		= "those are",
		["those've"]		= "those have",
		["'thout"]			= "without",
		["'til"]			= "until",
		["'tis"]			= "it is",
		["to've"]			= "to have",
		["tryna"]			= "trying to",
		["'twas"]			= "it was",
		["'tween"]			= "between",
		["'twere"]			= "it were",
		["w'all"]			= "we all",
		["w'at"]			= "we at",
		["wanna"]			= "want to",
		["wasn't"]			= "was not",
		["we'd've"]			= "we would have",
		["we'll"]			= "we will",
		["we're"]			= "we are",
		["we've"]			= "we have",
		["weren't"]			= "were not",
		["whatcha"]			= "what are you",
		["what'd"]			= "what did",
		["what'll"]			= "what will",
		["what've"]			= "what have",
		["when'd"]			= "when did",
		["where'd"]			= "where did",
		["where're"]		= "where are",
		["where've"]		= "where have",
		["which're"]		= "which are",
		["which've"]		= "which have",
		["who'd've"]		= "who would have",
		["who're"]			= "who are",
		["who've"]			= "who have",
		["why'd"]			= "why did",
		["why'dja"]			= "why did you",
		["why're"]			= "why are",
		["willn't"]			= "will not",
		["won't"]			= "will not",
		["wonnot"]			= "will not",
		["would've"]		= "would have",
		["wouldn't"]		= "would not",
		["wouldn't've"]		= "would not have",
		["y'at"]			= "you at",
		["y'ever"]			= "have you ever",
		["y'know"]			= "you know",
		["yessir"]			= "yes sir",
		["you'll"]			= "you will",
		["you're"]			= "you are",
		["you've"]			= "you have",

		-- shared elven
		["blood elf"]				= "sin'dorei",
		["blood elves"]				= "sin'dorei",
		["blood elven"]				= "sin'dorei",
		["void elf"]				= "ren'dorei",
		["void elves"]				= "ren'dorei",
		["void elven"]				= "ren'dorei",
		["high elf"]				= "quel'dorei",
		["high elves"]				= "quel'dorei",
		["high elven"]				= "quel'dorei",
		["night elf"]				= "kaldorei",
		["night elves"]				= "kaldorei",
		["night elven"]				= "kaldorei",
		["children of blood"]		= "sin'dorei",
		["children of the blood"]	= "sin'dorei",
		["children of the sun"]		= "belore'dorei",
		["children of sun"]			= "belore'dorei",
		["children of the void"]	= "ren'dorei",
		["children of void"]		= "ren'dorei",
		["children of noble birth"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["child of blood"]			= "sin'dorei",
		["child of the blood"]		= "sin'dorei",
		["child of the sun"]		= "belore'dorei",
		["child of sun"]			= "belore'dorei",
		["child of the void"]		= "ren'dorei",
		["child of void"]			= "ren'dorei",
		["child of noble birth"]	= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["people of blood"]			= "sin'dorei",
		["people of the blood"]		= "sin'dorei",
		["people of the sun"]		= "belore'dorei",
		["people of sun"]			= "belore'dorei",
		["people of the void"]		= "ren'dorei",
		["people of void"]			= "ren'dorei",
		["people of noble birth"]	= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["person of blood"]			= "sin'dorei",
		["person of the blood"]		= "sin'dorei",
		["person of the sun"]		= "belore'dorei",
		["person of sun"]			= "belore'dorei",
		["person of the void"]		= "ren'dorei",
		["person of void"]			= "ren'dorei",
		["person of noble birth"]	= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["highborne"]				= "quel'dorei",
		["highbornes"]				= "quel'dorei",
		["children of the stars"]	= "kaldorei",
		["children of stars"]		= "kaldorei",
		["nightborne"]				= "shal'dorei",
		["nightbornes"]				= "shal'dorei",
		["children of shadow"]		= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["children of the night"]	= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["high home"]				= "Quel'Thalas",


		-- core greetings & farewells
		["safe travels"]			= "al diel shala",
		["speak your business"]		= "anaria shola",
		["greetings, traveler"]		= "bal'a dash, malanore",
		["greetings traveler"]		= "bal'a dash malanore",
		["farewell"]				= "shorel'aran",
		["fare well"]				= "shorel'aran",
		["well met"]				= "sinu a'manore",
	},

	[L["Darnassian"]] = {
		-- shared elven
		["blood elf"]				= "sin'dorei",
		["blood elves"]				= "sin'dorei",
		["blood elven"]				= "sin'dorei",
		["void elf"]				= "ren'dorei",
		["void elves"]				= "ren'dorei",
		["void elven"]				= "ren'dorei",
		["high elf"]				= "quel'dorei",
		["high elves"]				= "quel'dorei",
		["high elven"]				= "quel'dorei",
		["night elf"]				= "kaldorei",
		["night elves"]				= "kaldorei",
		["night elven"]				= "kaldorei",
		["children of blood"]		= "sin'dorei",
		["children of the blood"]	= "sin'dorei",
		["children of the sun"]		= "belore'dorei",
		["children of sun"]			= "belore'dorei",
		["children of the void"]	= "ren'dorei",
		["children of void"]		= "ren'dorei",
		["children of noble birth"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["child of blood"]			= "sin'dorei",
		["child of the blood"]		= "sin'dorei",
		["child of the sun"]		= "belore'dorei",
		["child of sun"]			= "belore'dorei",
		["child of the void"]		= "ren'dorei",
		["child of void"]			= "ren'dorei",
		["child of noble birth"]	= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["people of blood"]			= "sin'dorei",
		["people of the blood"]		= "sin'dorei",
		["people of the sun"]		= "belore'dorei",
		["people of sun"]			= "belore'dorei",
		["people of the void"]		= "ren'dorei",
		["people of void"]			= "ren'dorei",
		["people of noble birth"]	= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["person of blood"]			= "sin'dorei",
		["person of the blood"]		= "sin'dorei",
		["person of the sun"]		= "belore'dorei",
		["person of sun"]			= "belore'dorei",
		["person of the void"]		= "ren'dorei",
		["person of void"]			= "ren'dorei",
		["person of noble birth"]	= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["highborne"]				= "quel'dorei",
		["highbornes"]				= "quel'dorei",
		["children of the stars"]	= "kaldorei",
		["children of stars"]		= "kaldorei",
		["nightborne"]				= "shal'dorei",
		["nightbornes"]				= "shal'dorei",
		["children of shadow"]		= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["children of the night"]	= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["high home"]				= "Quel'Thalas",

		-- core greetings & farewells
		["elune be with you"]				= "Elune-Adore",
		["good fortune to you"]				= "ishnu-alah",
		["good fortunate to your family"]	= "ishnu-dal-dieb",

		-- faith, elune, & the wilds
		["the moon"]						= "Elune",
		["the white lady"]					= "Elune",
	},

	[L["Mechagnome"]] = {
		-- de-contract, overly formal
		["gonna"]			= "going to",
		["'em"]				= "them",
		["'bout"]			= "about",
		["'cause"]			= "because",
		["cuz"]				= "because",
		["'cept"]			= "except",
		["c'mon"]			= "come on",
		["'n"]				= "and",
		["'n'"]				= "and",
		["n"]				= "and",
		["a'ight"]			= "alright",
		["ain't"]			= "is not",
		["amn't"]			= "am not",
		["aren't"]			= "are not",
		["can't"]			= "cannot",
		["cap'n"]			= "captain",
		["could've"]		= "could have",
		["couldn't"]		= "could not",
		["couldn't've"]		= "could not have",
		["cuppa"]			= "cup of",
		["daren't"]			= "dare not",
		["daresn't"]		= "dare not",
		["dasn't"]			= "dare not",
		["didn't"]			= "did not",
		["doesn't"]			= "does not",
		["don't"]			= "do not",
		["dunno"]			= "do not know",
		["d'ye"]			= "do you",
		["d'ya"]			= "do you",
		["'gainst"]			= "against",
		["g'day"]			= "good day",
		["gimme"]			= "give me",
		["giv'n"]			= "given",
		["hadn't"]			= "had not",
		["had've"]			= "had have",
		["hasn't"]			= "has not",
		["he'll"]			= "he will",
		["here's"]			= "here is",
		["how'd"]			= "how did",
		["how'll"]			= "how will",
		["how're"]			= "how are",
		["i'd"]				= "i would",
		["i'd've"]			= "i would have",
		["i'd'nt"]			= "i would not",
		["if'n"]			= "if and when",
		["i'll"]			= "i will",
		["i'm"]				= "i am",
		["i'm'onna"]		= "i am going to",
		["imma"]			= "i am going to",
		["i'm'o"]			= "i am going to",
		["i'm'na"]			= "i am going to",
		["innit"]			= "isn't it",
		["i've"]			= "i have",
		["isn't"]			= "is not",
		["it'd"]			= "it would",
		["it'll"]			= "it will",
		["it's"]			= "it's",
		["kinda"]			= "kind of",
		["lemme"]			= "let me",
		["lemmi"]			= "let me",
		["let's"]			= "let us",
		["may've"]			= "may have",
		["methinks"]		= "i think",
		["mightn't"]		= "might not",
		["might've"]		= "might have",
		["mine's"]			= "mine is",
		["mustn't"]			= "must not",
		["mustn't've"]		= "must not have",
		["must've"]			= "must have",
		["'neath"]			= "beneath",
		["needn't"]			= "need not",
		["ne'er"]			= "never",
		["o'clock"]			= "of the clock",
		["o'er"]			= "over",
		["ol'"]				= "old",
		["ought've"]		= "ought have",
		["oughtn't"]		= "ought not",
		["oughtn't've"]		= "ought not have",
		["'round"]			= "around",
		["shalln't"]		= "shall not",
		["shan'"]			= "shall not",
		["shan't"]			= "shall not",
		["should've"]		= "should have",
		["shouldn't"]		= "should not",
		["shouldn't've"]	= "should not have",
		["so're"]			= "so are",
		["so've"]			= "so have",
		["that're"]			= "that are",
		["there'll"]		= "there will",
		["there're"]		= "there are",
		["these're"]		= "these are",
		["these've"]		= "these have",
		["they'll"]			= "they will",
		["they've"]			= "they have",
		["those're"]		= "those are",
		["those've"]		= "those have",
		["'thout"]			= "without",
		["'til"]			= "until",
		["'tis"]			= "it is",
		["to've"]			= "to have",
		["tryna"]			= "trying to",
		["'twas"]			= "it was",
		["'tween"]			= "between",
		["'twere"]			= "it were",
		["w'all"]			= "we all",
		["w'at"]			= "we at",
		["wanna"]			= "want to",
		["wasn't"]			= "was not",
		["we'd've"]			= "we would have",
		["we'll"]			= "we will",
		["we're"]			= "we are",
		["we've"]			= "we have",
		["weren't"]			= "were not",
		["whatcha"]			= "what are you",
		["what'd"]			= "what did",
		["what'll"]			= "what will",
		["what've"]			= "what have",
		["when'd"]			= "when did",
		["where'd"]			= "where did",
		["where're"]		= "where are",
		["where've"]		= "where have",
		["which're"]		= "which are",
		["which've"]		= "which have",
		["who'd've"]		= "who would have",
		["who're"]			= "who are",
		["who've"]			= "who have",
		["why'd"]			= "why did",
		["why'dja"]			= "why did you",
		["why're"]			= "why are",
		["willn't"]			= "will not",
		["won't"]			= "will not",
		["wonnot"]			= "will not",
		["would've"]		= "would have",
		["wouldn't"]		= "would not",
		["wouldn't've"]		= "would not have",
		["y'at"]			= "you at",
		["y'ever"]			= "have you ever",
		["y'know"]			= "you know",
		["yessir"]			= "yes sir",
		["you'll"]			= "you will",
		["you're"]			= "you are",
		["you've"]			= "you have",



		-- thinking, planning, & invention

		["think"]			= "calculate",
		["thinking"]		= "processing",
		["thought"]			= "idea unit",
		["plan"]			= "blueprint",
		["lever"]			= "manual activator",
		["helper"]			= "assistant unit",
		["destroyed"]		= "temporarily nonfunctional",
		["unsafe"]			= "theoretically survivable",

		-- emotion
		["happy"]			= "operating optimally",
		["excited"]			= "overclocked",
		["angry"]			= "mal-functioning",
		["mad"]				= "logic-compromised",
		["sad"]				= "low power",
		["now"]				= "immediately",
		["soon"]			= "shortly",

		-- affirmation & negation
		["yes"]				= "affirmative",
		["yeah"]			= "affirmative",
		["no"]				= "negative",

		-- mild insults
		["idiot"]			= "malfunctioning unit",
		["crazy"]			= "creatively unstable",
	},

	[L["DarkspearTrolls"]] = {
		-- contractions (review these later)
		["going to"]		= "gonna",
		["them"]			= "'em",
		["about"]			= "'bout",
		["because"]			= "'cause",
		["except"]			= "'cept",
		["come on"]			= "c'mon",
		["and"]				= "'n",
		["alright"]			= "a'ight",
		["is not"]			= "ain't",
		["am not"]			= "amn't",
		["are not"]			= "aren't",
		["cannot"]			= "can't",
		["captain"]			= "cap'n",
		["could have"]		= "could've",
		["could not"]		= "couldn't",
		["could not have"]	= "couldn't've",
		["cup of"]			= "cuppa",
		["dare not"]		= "daren't",
		["dare not"]		= "daresn't",
		["dare not"]		= "dasn't",
		["did not"]			= "didn't",
		["does not"]		= "doesn't",
		["do not"]			= "don't",
		["do not know"]		= "dunno",
		["do you"]			= "d'ye",
		["do you"]			= "d'ya",
		["against"]			= "'gainst",
		["good day"]		= "g'day",
		["give me"]			= "gimme",
		["given"]			= "giv'n",
		["had not"]			= "hadn't",
		["had have"]		= "had've",
		["has not"]			= "hasn't",
		["he will"]			= "he'll",
		["here is"]			= "here's",
		["how did"]			= "how'd",
		["how will"]		= "how'll",
		["how are"]			= "how're",
		["i would"]			= "i'd",
		["i would have"]	= "i'd've",
		["i would not"]		= "i'd'nt",
		["if and when"]		= "if'n",
		["i will"]			= "i'll",
		["i am"]			= "i'm",
		["i am going to"]	= "i'm'onna",
		["i am going to"]	= "imma",
		["i am going to"]	= "i'm'o",
		["i am going to"]	= "i'm'na",
		["isn't it"]		= "innit",
		["i have"]			= "i've",
		["is not"]			= "isn't",
		["it would"]		= "it'd",
		["it will"]			= "it'll",
		["it's"]			= "it's",
		["kind of"]			= "kinda",
		["let me"]			= "lemme",
		["let me"]			= "lemmi",
		["let us"]			= "let's",
		["may have"]		= "may've",
		["i think"]			= "methinks",
		["might not"]		= "mightn't",
		["might have"]		= "might've",
		["mine is"]			= "mine's",
		["must not"]		= "mustn't",
		["must not have"]	= "mustn't've",
		["must have"]		= "must've",
		["beneath"]			= "'neath",
		["need not"]		= "needn't",
		--["never"]			= "ne'er",
		["of the clock"]	= "o'clock",
		["over"]			= "o'er",
		["old"]				= "ol'",
		["ought have"]		= "ought've",
		["ought not"]		= "oughtn't",
		["ought not have"]	= "oughtn't've",
		["around"]			= "'round",
		["shall not"]		= "shalln't",
		["shall not"]		= "shan'",
		["shall not"]		= "shan't",
		["should have"]		= "should've",
		["should not"]		= "shouldn't",
		["should not have"]	= "shouldn't've",
		["so are"]			= "so're",
		["so have"]			= "so've",
		["that are"]		= "that're",
		["there will"]		= "there'll",
		["there are"]		= "there're",
		["these are"]		= "these're",
		["these have"]		= "these've",
		["they will"]		= "they'll",
		["they have"]		= "they've",
		["those are"]		= "those're",
		["those have"]		= "those've",
		["without"]			= "'thout",
		["until"]			= "'til",
		["it is"]			= "'tis",
		["to have"]			= "to've",
		["trying to"]		= "tryna",
		["it was"]			= "'twas",
		["between"]			= "'tween",
		["it were"]			= "'twere",
		["we all"]			= "w'all",
		["we at"]			= "w'at",
		["want to"]			= "wanna",
		["was not"]			= "wasn't",
		["we would have"]	= "we'd've",
		["we will"]			= "we'll",
		["we are"]			= "we're",
		["we have"]			= "we've",
		["were not"]		= "weren't",
		["what are you"]	= "whatcha",
		["what did"]		= "what'd",
		["what will"]		= "what'll",
		["what have"]		= "what've",
		["when did"]		= "when'd",
		["where did"]		= "where'd",
		["where are"]		= "where're",
		["where have"]		= "where've",
		["which are"]		= "which're",
		["which have"]		= "which've",
		["who would have"]	= "who'd've",
		["who are"]			= "who're",
		["who have"]		= "who've",
		["why did"]			= "why'd",
		["why did you"]		= "why'dja",
		["why are"]			= "why're",
		["will not"]		= "willn't",
		["will not"]		= "won't",
		["will not"]		= "wonnot",
		["would have"]		= "would've",
		["would not"]		= "wouldn't",
		["would not have"]	= "wouldn't've",
		["you at"]			= "y'at",
		["have you ever"]	= "y'ever",
		["you know"]		= "y'know",
		["yes sir"]			= "yessir",
		["you will"]		= "you'll",
		["you are"]			= "you're",
		["you have"]		= "you've",


		-- core speech & phonetics
		["no"]				= "nah",
		["nothing"]			= "no tin'",
		["something"]		= "somet'ing",
		["is"]				= "be",
		["this"]			= "dis",
		["that"]			= "dat",
		["there"]			= "dere",
		["the"]				= "de",

		["with"]			= "wit'",
		["without"]			= "wit'out",

		["for"]				= "fo'",

		["me"]				= "mi",
		["my"]				= "me",
		["mine"]			= "mi own",

		["your"]			= "yer",
		["yours"]			= "yers",

		["we"]				= "we",
		["us"]				= "us",
		["our"]				= "we",
		["later"]			= "laytah",
		["forever"]			= "forevah",

		-- questions & connectors
		["what"]			= "wha'",
		["where"]			= "whe'",

		["and"]				= "an'",
		["or"]				= "or",
		["but"]				= "but",

		-- greetings & social rhythm
		["hello"]			= "'ello",
		["hi"]				= "'ey",
		["hey"]				= "'ey",


		["thanks"]			= "t'anks",
		["thank you"]		= "t'ank ya",

		-- people & social identity
		["brother"]		 	= "brudda",
		["brothers"]		= "bruddas",
		["sister"]			= "sistah",
		["sisters"]			= "sistahs",
		["stranger"]		= "stranga",
		["man"]				= "mon",

		["black magic"]		= "voodoo",
		["ancient magic"]	= "voodoo",
		["power"]			= "juju",

	},

	[L["Goblin"]] = {
		["about"]			= "'bout",
		["around"]			= "'round",

		["going"]			= "goin'",
		["doing"]			= "doin'",
		["getting"]			= "gettin'",

		["hey"]				= "ey",

		["all of you"]		= "all of yous",
		["see you"]			= "see ya",

		-- affirmation, negation, & attitude
		["yes"]				= "yeah",
		["yeah"]			= "yeah",


		-- people & insults
		["friend"]			= "pal",
		["friends"]			= "pals",

		["enemy"]			= "jerk",
		["idiot"]			= "moron",
		["fool"]			= "chump",
	},

	[L["Sailor"]] = { -- pirate and sailor kul tiran
		-- core grammar & pronouns
		["i am"]			= "i be",
		["i was"]			= "i were",
		["you are"]			= "ye be",
		["we are"]			= "we be",
		["they are"]		= "they be",

		["was"]				= "were",
		["were"]			= "were",

		["myself"]			= "meself",
		["yourself"]		= "yerself",
		["your"]			= "yer",
		["yours"]			= "yers",

		["them"]			= "'em",
		["those"]			= "them",
		["these"]			= "them",

		-- greetings, farewells, & address
		["goodbye"]			= "fare ye well",
		["bye"]			 	= "fare ye well",
		["see you"]			= "fair winds",

		["sir"]				= "matey",
		["madam"]			= "mum",
		["miss"]			= "lass",
		["boy"]				= "lad",
		["girl"]			= "lass",

		["everyone"]		= "er'ryone",

		-- agreement, disagreement, & reactions
		["okay"]			= "aye",
		["ok"]				= "aye",
		["no"]				= "nay",
		["never"]			= "ne'er",


		["here"]			= "'ere",
		["over there"]		= "over yonder",
		["there"]			= "thar",
		["captain"]			= "cap'n",

		-- combat & danger
		["enemy"]			= "en'my",
		["enemies"]			= "en'mies",
		["upon"]			= "'pon",


		-- orders & discipline
		["cancel"]			= "belay",

		["calm"]			= "steady",


		-- insults
		["idiot"]			= "landlubber",
		["fool"]			= "lubber",


		-- food, drink, & daily life
		["food"]			= "grub",

		["starving"]		= "starvin'",


		-- emphasis & filler
		["very"]			= "mighty",

	},

	[L["KulTiranNoble"]] = { -- interior southern boralus has more of this
		["cup of"]			= "cuppa",

		["ma'am"]			= "madam",
		["maam"]			= "madam",

		["good"]			= "splendid",
		["great"]			= "marvelous",
		["excellent"]		= "splendid",
		["amazing"]			= "marvelous",
		["handsome"]		= "dashing",
		["beautiful"]		= "ravishing",

		["very"]			= "terribly",
		["really"]			= "terribly",
		["completely"]		= "utterly",
		["totally"]			= "utterly",

		["fix up"]			= "spruce up",
		["improve"]			= "spruce up",
		["toilet"]			= "lavatory",

		["booze"]			= "alcohol",
		["drink"]			= "champagne",

		["hey"]				= "hello",
		["banter"]			= "repartee",

		["very good"]		= "jolly well done",
		["you should"]		= "you would do well to",
		["you shouldn't"]	= "you would do well not to",
	},

	[L["Highborne"]] = {
		-- de-contract, overly formal
		["gonna"]			= "going to",
		["'em"]				= "them",
		["'bout"]			= "about",
		["'cause"]			= "because",
		["cuz"]				= "because",
		["'cept"]			= "except",
		["c'mon"]			= "come on",
		["'n"]				= "and",
		["'n'"]				= "and",
		["n"]				= "and",
		["a'ight"]			= "alright",
		["ain't"]			= "is not",
		["amn't"]			= "am not",
		["aren't"]			= "are not",
		["can't"]			= "cannot",
		["cap'n"]			= "captain",
		["could've"]		= "could have",
		["couldn't"]		= "could not",
		["couldn't've"]		= "could not have",
		["cuppa"]			= "cup of",
		["daren't"]			= "dare not",
		["daresn't"]		= "dare not",
		["dasn't"]			= "dare not",
		["didn't"]			= "did not",
		["doesn't"]			= "does not",
		["don't"]			= "do not",
		["dunno"]			= "do not know",
		["d'ye"]			= "do you",
		["d'ya"]			= "do you",
		["'gainst"]			= "against",
		["g'day"]			= "good day",
		["gimme"]			= "give me",
		["giv'n"]			= "given",
		["hadn't"]			= "had not",
		["had've"]			= "had have",
		["hasn't"]			= "has not",
		["he'll"]			= "he will",
		["here's"]			= "here is",
		["how'd"]			= "how did",
		["how'll"]			= "how will",
		["how're"]			= "how are",
		["i'd"]				= "i would",
		["i'd've"]			= "i would have",
		["i'd'nt"]			= "i would not",
		["if'n"]			= "if and when",
		["i'll"]			= "i will",
		["i'm"]				= "i am",
		["i'm'onna"]		= "i am going to",
		["imma"]			= "i am going to",
		["i'm'o"]			= "i am going to",
		["i'm'na"]			= "i am going to",
		["innit"]			= "isn't it",
		["i've"]			= "i have",
		["isn't"]			= "is not",
		["it'd"]			= "it would",
		["it'll"]			= "it will",
		["it's"]			= "it's",
		["kinda"]			= "kind of",
		["lemme"]			= "let me",
		["lemmi"]			= "let me",
		["let's"]			= "let us",
		["may've"]			= "may have",
		["methinks"]		= "i think",
		["mightn't"]		= "might not",
		["might've"]		= "might have",
		["mine's"]			= "mine is",
		["mustn't"]			= "must not",
		["mustn't've"]		= "must not have",
		["must've"]			= "must have",
		["'neath"]			= "beneath",
		["needn't"]			= "need not",
		["ne'er"]			= "never",
		["o'clock"]			= "of the clock",
		["o'er"]			= "over",
		["ol'"]				= "old",
		["ought've"]		= "ought have",
		["oughtn't"]		= "ought not",
		["oughtn't've"]		= "ought not have",
		["'round"]			= "around",
		["shalln't"]		= "shall not",
		["shan'"]			= "shall not",
		["shan't"]			= "shall not",
		["should've"]		= "should have",
		["shouldn't"]		= "should not",
		["shouldn't've"]	= "should not have",
		["so're"]			= "so are",
		["so've"]			= "so have",
		["that're"]			= "that are",
		["there'll"]		= "there will",
		["there're"]		= "there are",
		["these're"]		= "these are",
		["these've"]		= "these have",
		["they'll"]			= "they will",
		["they've"]			= "they have",
		["those're"]		= "those are",
		["those've"]		= "those have",
		["'thout"]			= "without",
		["'til"]			= "until",
		["'tis"]			= "it is",
		["to've"]			= "to have",
		["tryna"]			= "trying to",
		["'twas"]			= "it was",
		["'tween"]			= "between",
		["'twere"]			= "it were",
		["w'all"]			= "we all",
		["w'at"]			= "we at",
		["wanna"]			= "want to",
		["wasn't"]			= "was not",
		["we'd've"]			= "we would have",
		["we'll"]			= "we will",
		["we're"]			= "we are",
		["we've"]			= "we have",
		["weren't"]			= "were not",
		["whatcha"]			= "what are you",
		["what'd"]			= "what did",
		["what'll"]			= "what will",
		["what've"]			= "what have",
		["when'd"]			= "when did",
		["where'd"]			= "where did",
		["where're"]		= "where are",
		["where've"]		= "where have",
		["which're"]		= "which are",
		["which've"]		= "which have",
		["who'd've"]		= "who would have",
		["who're"]			= "who are",
		["who've"]			= "who have",
		["why'd"]			= "why did",
		["why'dja"]			= "why did you",
		["why're"]			= "why are",
		["willn't"]			= "will not",
		["won't"]			= "will not",
		["wonnot"]			= "will not",
		["would've"]		= "would have",
		["wouldn't"]		= "would not",
		["wouldn't've"]		= "would not have",
		["y'at"]			= "you at",
		["y'ever"]			= "have you ever",
		["y'know"]			= "you know",
		["yessir"]			= "yes sir",
		["you'll"]			= "you will",
		["you're"]			= "you are",
		["you've"]			= "you have",

		-- shared elven
		["blood elf"]				= "sin'dorei",
		["blood elves"]				= "sin'dorei",
		["blood elven"]				= "sin'dorei",
		["void elf"]				= "ren'dorei",
		["void elves"]				= "ren'dorei",
		["void elven"]				= "ren'dorei",
		["high elf"]				= "quel'dorei",
		["high elves"]				= "quel'dorei",
		["high elven"]				= "quel'dorei",
		["night elf"]				= "kaldorei",
		["night elves"]				= "kaldorei",
		["night elven"]				= "kaldorei",
		["children of blood"]		= "sin'dorei",
		["children of the blood"]	= "sin'dorei",
		["children of the sun"]		= "belore'dorei",
		["children of sun"]			= "belore'dorei",
		["children of the void"]	= "ren'dorei",
		["children of void"]		= "ren'dorei",
		["children of noble birth"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["child of blood"]			= "sin'dorei",
		["child of the blood"]		= "sin'dorei",
		["child of the sun"]		= "belore'dorei",
		["child of sun"]			= "belore'dorei",
		["child of the void"]		= "ren'dorei",
		["child of void"]			= "ren'dorei",
		["child of noble birth"]	= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["people of blood"]			= "sin'dorei",
		["people of the blood"]		= "sin'dorei",
		["people of the sun"]		= "belore'dorei",
		["people of sun"]			= "belore'dorei",
		["people of the void"]		= "ren'dorei",
		["people of void"]			= "ren'dorei",
		["people of noble birth"]	= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["person of blood"]			= "sin'dorei",
		["person of the blood"]		= "sin'dorei",
		["person of the sun"]		= "belore'dorei",
		["person of sun"]			= "belore'dorei",
		["person of the void"]		= "ren'dorei",
		["person of void"]			= "ren'dorei",
		["person of noble birth"]	= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["highborne"]				= "quel'dorei",
		["highbornes"]				= "quel'dorei",
		["children of the stars"]	= "kaldorei",
		["children of stars"]		= "kaldorei",
		["nightborne"]				= "shal'dorei",
		["nightbornes"]				= "shal'dorei",
		["children of shadow"]		= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["children of the night"]	= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["high home"]				= "Quel'Thalas",

	},

	[L["Nightborne"]] = {
		-- de-contract, overly formal
		["gonna"]			= "going to",
		["'em"]				= "them",
		["'bout"]			= "about",
		["'cause"]			= "because",
		["cuz"]				= "because",
		["'cept"]			= "except",
		["c'mon"]			= "come on",
		["'n"]				= "and",
		["'n'"]				= "and",
		["n"]				= "and",
		["a'ight"]			= "alright",
		["ain't"]			= "is not",
		["amn't"]			= "am not",
		["aren't"]			= "are not",
		["can't"]			= "cannot",
		["cap'n"]			= "captain",
		["could've"]		= "could have",
		["couldn't"]		= "could not",
		["couldn't've"]		= "could not have",
		["cuppa"]			= "cup of",
		["daren't"]			= "dare not",
		["daresn't"]		= "dare not",
		["dasn't"]			= "dare not",
		["didn't"]			= "did not",
		["doesn't"]			= "does not",
		["don't"]			= "do not",
		["dunno"]			= "do not know",
		["d'ye"]			= "do you",
		["d'ya"]			= "do you",
		["'gainst"]			= "against",
		["g'day"]			= "good day",
		["gimme"]			= "give me",
		["giv'n"]			= "given",
		["hadn't"]			= "had not",
		["had've"]			= "had have",
		["hasn't"]			= "has not",
		["he'll"]			= "he will",
		["here's"]			= "here is",
		["how'd"]			= "how did",
		["how'll"]			= "how will",
		["how're"]			= "how are",
		["i'd"]				= "i would",
		["i'd've"]			= "i would have",
		["i'd'nt"]			= "i would not",
		["if'n"]			= "if and when",
		["i'll"]			= "i will",
		["i'm"]				= "i am",
		["i'm'onna"]		= "i am going to",
		["imma"]			= "i am going to",
		["i'm'o"]			= "i am going to",
		["i'm'na"]			= "i am going to",
		["innit"]			= "isn't it",
		["i've"]			= "i have",
		["isn't"]			= "is not",
		["it'd"]			= "it would",
		["it'll"]			= "it will",
		["it's"]			= "it's",
		["kinda"]			= "kind of",
		["lemme"]			= "let me",
		["lemmi"]			= "let me",
		["let's"]			= "let us",
		["may've"]			= "may have",
		["methinks"]		= "i think",
		["mightn't"]		= "might not",
		["might've"]		= "might have",
		["mine's"]			= "mine is",
		["mustn't"]			= "must not",
		["mustn't've"]		= "must not have",
		["must've"]			= "must have",
		["'neath"]			= "beneath",
		["needn't"]			= "need not",
		["ne'er"]			= "never",
		["o'clock"]			= "of the clock",
		["o'er"]			= "over",
		["ol'"]				= "old",
		["ought've"]		= "ought have",
		["oughtn't"]		= "ought not",
		["oughtn't've"]		= "ought not have",
		["'round"]			= "around",
		["shalln't"]		= "shall not",
		["shan'"]			= "shall not",
		["shan't"]			= "shall not",
		["should've"]		= "should have",
		["shouldn't"]		= "should not",
		["shouldn't've"]	= "should not have",
		["so're"]			= "so are",
		["so've"]			= "so have",
		["that're"]			= "that are",
		["there'll"]		= "there will",
		["there're"]		= "there are",
		["these're"]		= "these are",
		["these've"]		= "these have",
		["they'll"]			= "they will",
		["they've"]			= "they have",
		["those're"]		= "those are",
		["those've"]		= "those have",
		["'thout"]			= "without",
		["'til"]			= "until",
		["'tis"]			= "it is",
		["to've"]			= "to have",
		["tryna"]			= "trying to",
		["'twas"]			= "it was",
		["'tween"]			= "between",
		["'twere"]			= "it were",
		["w'all"]			= "we all",
		["w'at"]			= "we at",
		["wanna"]			= "want to",
		["wasn't"]			= "was not",
		["we'd've"]			= "we would have",
		["we'll"]			= "we will",
		["we're"]			= "we are",
		["we've"]			= "we have",
		["weren't"]			= "were not",
		["whatcha"]			= "what are you",
		["what'd"]			= "what did",
		["what'll"]			= "what will",
		["what've"]			= "what have",
		["when'd"]			= "when did",
		["where'd"]			= "where did",
		["where're"]		= "where are",
		["where've"]		= "where have",
		["which're"]		= "which are",
		["which've"]		= "which have",
		["who'd've"]		= "who would have",
		["who're"]			= "who are",
		["who've"]			= "who have",
		["why'd"]			= "why did",
		["why'dja"]			= "why did you",
		["why're"]			= "why are",
		["willn't"]			= "will not",
		["won't"]			= "will not",
		["wonnot"]			= "will not",
		["would've"]		= "would have",
		["wouldn't"]		= "would not",
		["wouldn't've"]		= "would not have",
		["y'at"]			= "you at",
		["y'ever"]			= "have you ever",
		["y'know"]			= "you know",
		["yessir"]			= "yes sir",
		["you'll"]			= "you will",
		["you're"]			= "you are",
		["you've"]			= "you have",

		-- shared elven
		["blood elf"]				= "sin'dorei",
		["blood elves"]				= "sin'dorei",
		["blood elven"]				= "sin'dorei",
		["void elf"]				= "ren'dorei",
		["void elves"]				= "ren'dorei",
		["void elven"]				= "ren'dorei",
		["high elf"]				= "quel'dorei",
		["high elves"]				= "quel'dorei",
		["high elven"]				= "quel'dorei",
		["night elf"]				= "kaldorei",
		["night elves"]				= "kaldorei",
		["night elven"]				= "kaldorei",
		["children of blood"]		= "sin'dorei",
		["children of the blood"]	= "sin'dorei",
		["children of the sun"]		= "belore'dorei",
		["children of sun"]			= "belore'dorei",
		["children of the void"]	= "ren'dorei",
		["children of void"]		= "ren'dorei",
		["children of noble birth"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["children of nobility"]	= "quel'dorei",
		["child of blood"]			= "sin'dorei",
		["child of the blood"]		= "sin'dorei",
		["child of the sun"]		= "belore'dorei",
		["child of sun"]			= "belore'dorei",
		["child of the void"]		= "ren'dorei",
		["child of void"]			= "ren'dorei",
		["child of noble birth"]	= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["child of nobility"]		= "quel'dorei",
		["people of blood"]			= "sin'dorei",
		["people of the blood"]		= "sin'dorei",
		["people of the sun"]		= "belore'dorei",
		["people of sun"]			= "belore'dorei",
		["people of the void"]		= "ren'dorei",
		["people of void"]			= "ren'dorei",
		["people of noble birth"]	= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["people of nobility"]		= "quel'dorei",
		["person of blood"]			= "sin'dorei",
		["person of the blood"]		= "sin'dorei",
		["person of the sun"]		= "belore'dorei",
		["person of sun"]			= "belore'dorei",
		["person of the void"]		= "ren'dorei",
		["person of void"]			= "ren'dorei",
		["person of noble birth"]	= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["person of nobility"]		= "quel'dorei",
		["highborne"]				= "quel'dorei",
		["highbornes"]				= "quel'dorei",
		["children of the stars"]	= "kaldorei",
		["children of stars"]		= "kaldorei",
		["nightborne"]				= "shal'dorei",
		["nightbornes"]				= "shal'dorei",
		["children of shadow"]		= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["children of the night"]	= "shal'dorei", -- technically not canon, we're guessing because shal = shadow, maybe night = nightwell
		["high home"]				= "Quel'Thalas",

	},

	[L["Zandalari"]] = {
		-- de-contract, overly formal
		["gonna"]			= "going to",
		["'em"]				= "them",
		["'bout"]			= "about",
		["'cause"]			= "because",
		["cuz"]				= "because",
		["'cept"]			= "except",
		["c'mon"]			= "come on",
		["'n"]				= "and",
		["'n'"]				= "and",
		["n"]				= "and",
		["a'ight"]			= "alright",
		["ain't"]			= "is not",
		["amn't"]			= "am not",
		["aren't"]			= "are not",
		["can't"]			= "cannot",
		["cap'n"]			= "captain",
		["could've"]		= "could have",
		["couldn't"]		= "could not",
		["couldn't've"]		= "could not have",
		["cuppa"]			= "cup of",
		["daren't"]			= "dare not",
		["daresn't"]		= "dare not",
		["dasn't"]			= "dare not",
		["didn't"]			= "did not",
		["doesn't"]			= "does not",
		["don't"]			= "do not",
		["dunno"]			= "do not know",
		["d'ye"]			= "do you",
		["d'ya"]			= "do you",
		["'gainst"]			= "against",
		["g'day"]			= "good day",
		["gimme"]			= "give me",
		["giv'n"]			= "given",
		["hadn't"]			= "had not",
		["had've"]			= "had have",
		["hasn't"]			= "has not",
		["he'll"]			= "he will",
		["here's"]			= "here is",
		["how'd"]			= "how did",
		["how'll"]			= "how will",
		["how're"]			= "how are",
		["i'd"]				= "i would",
		["i'd've"]			= "i would have",
		["i'd'nt"]			= "i would not",
		["if'n"]			= "if and when",
		["i'll"]			= "i will",
		["i'm"]				= "i am",
		["i'm'onna"]		= "i am going to",
		["imma"]			= "i am going to",
		["i'm'o"]			= "i am going to",
		["i'm'na"]			= "i am going to",
		["innit"]			= "isn't it",
		["i've"]			= "i have",
		["isn't"]			= "is not",
		["it'd"]			= "it would",
		["it'll"]			= "it will",
		["it's"]			= "it's",
		["kinda"]			= "kind of",
		["lemme"]			= "let me",
		["lemmi"]			= "let me",
		["let's"]			= "let us",
		["may've"]			= "may have",
		["methinks"]		= "i think",
		["mightn't"]		= "might not",
		["might've"]		= "might have",
		["mine's"]			= "mine is",
		["mustn't"]			= "must not",
		["mustn't've"]		= "must not have",
		["must've"]			= "must have",
		["'neath"]			= "beneath",
		["needn't"]			= "need not",
		["ne'er"]			= "never",
		["o'clock"]			= "of the clock",
		["o'er"]			= "over",
		["ol'"]				= "old",
		["ought've"]		= "ought have",
		["oughtn't"]		= "ought not",
		["oughtn't've"]		= "ought not have",
		["'round"]			= "around",
		["shalln't"]		= "shall not",
		["shan'"]			= "shall not",
		["shan't"]			= "shall not",
		["should've"]		= "should have",
		["shouldn't"]		= "should not",
		["shouldn't've"]	= "should not have",
		["so're"]			= "so are",
		["so've"]			= "so have",
		["that're"]			= "that are",
		["there'll"]		= "there will",
		["there're"]		= "there are",
		["these're"]		= "these are",
		["these've"]		= "these have",
		["they'll"]			= "they will",
		["they've"]			= "they have",
		["those're"]		= "those are",
		["those've"]		= "those have",
		["'thout"]			= "without",
		["'til"]			= "until",
		["'tis"]			= "it is",
		["to've"]			= "to have",
		["tryna"]			= "trying to",
		["'twas"]			= "it was",
		["'tween"]			= "between",
		["'twere"]			= "it were",
		["w'all"]			= "we all",
		["w'at"]			= "we at",
		["wanna"]			= "want to",
		["wasn't"]			= "was not",
		["we'd've"]			= "we would have",
		["we'll"]			= "we will",
		["we're"]			= "we are",
		["we've"]			= "we have",
		["weren't"]			= "were not",
		["whatcha"]			= "what are you",
		["what'd"]			= "what did",
		["what'll"]			= "what will",
		["what've"]			= "what have",
		["when'd"]			= "when did",
		["where'd"]			= "where did",
		["where're"]		= "where are",
		["where've"]		= "where have",
		["which're"]		= "which are",
		["which've"]		= "which have",
		["who'd've"]		= "who would have",
		["who're"]			= "who are",
		["who've"]			= "who have",
		["why'd"]			= "why did",
		["why'dja"]			= "why did you",
		["why're"]			= "why are",
		["willn't"]			= "will not",
		["won't"]			= "will not",
		["wonnot"]			= "will not",
		["would've"]		= "would have",
		["wouldn't"]		= "would not",
		["wouldn't've"]		= "would not have",
		["y'at"]			= "you at",
		["y'ever"]			= "have you ever",
		["y'know"]			= "you know",
		["yessir"]			= "yes sir",
		["you'll"]			= "you will",
		["you're"]			= "you are",
		["you've"]			= "you have",

	},

};

Lang.Dialects = Dialects